### ISSUE TITLE
TodoList

### ISSUE THREAD

**Issue by ImHype** [daisyjs/daisy.js#1]
There are some plans for Daisy development
* [x] eval expression 2017-10-3
* [x] ast -> virtual nodes 2017-10-3
* [x] simple virtual dom 2017-10-4 
* [x] events 2017-10-5
* [x] methods, directive, plugin, extends 2017-10-6
* [x] components 2017-10-7
* [ ] learn the edit Levenshtein distance algorithm and write the whole virtual dom 2017-10-14

**Comment by maczyt** [comment]
> 君羽牛逼

**Comment by ImHype** [comment]
@maczyt Thank you for praising
